version: '3.9'

services:
  backend:
    container_name: medinsight-backend
    build: .
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
    command: node app.js # Change as needed (e.g., npm run dev for dev mode)
    volumes:
      - .:/usr/src/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  db:
    container_name: medinsight-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  adminer:
    container_name: medinsight-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: ""
    command: >
      sh -c "certbot certonly --expand --webroot -w /var/www/certbot 
      --email jacinthdavid70@gmail.com 
      --agree-tos --no-eff-email 
      -d api.medinsight.mooo.com -d adminer.medinsight.mooo.com"
    depends_on:
      - nginx


networks:
  backend:

volumes:
  pgdata:

